Repository newrelic/node-newrelic-superagent, pull requests merged in 2020-07, with the labels that each got.

#31 Converts CI to github actions
  .github/workflows/ci-workflow.yml
  .travis.yml
Labels: risk:low, semver:patch

#34 Ignore vscode files
  .gitignore
Labels: ready-for-review, risk:none, semver:patch

#33 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
Labels: risk:low, semver:patch

#35 Added CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: ready-for-review, risk:none, semver:patch

#36 Added CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: ready-for-review, risk:none, semver:patch

#38 License
  LICENSE
  package.json
Labels: ready-for-review, risk:none, semver:minor

#39 Add third party notices
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: risk:low, semver:major

#41 changes branch for coveralls
  README.md
Labels: risk:low, semver:patch

#40 Copyright headers
  index.js
  lib/instrumentation.js
  nr-hooks.js
  tests/unit/newrelic.js
  tests/unit/superagent.tap.js
  tests/versioned/async-await.tap.js
  tests/versioned/newrelic.js
  tests/versioned/superagent.tap.js
Labels: ready-for-review, risk:none, semver:patch

#43 Removed usage of Coveralls.
  README.md
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: risk:low, semver:patch

#44 Updates readme to standard template with some content modifications.
  README.md
Labels: risk:low, semver:patch

#45 Adds additional items to npm ignore.
  .npmignore
Labels: risk:low, semver:patch

#46 Adds additional dependency language to bottom of third party notices
  THIRD_PARTY_NOTICES.md
Labels: risk:low, semver:patch

#48 Release v3.0.0
  CHANGELOG.md
  CONTRIBUTING.md
Labels: risk:low, semver:major

#50 Bumps node-test-utilities to ^4.0.0.
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: risk:low, semver:patch
